---
title: "Salary Web Final Project"
author: "Colin Glory, Jamie Nevin, and Ariana Cuba "
date: "2024-04-16"
output: html_document
---

```{r setup, include=FALSE}
#Run libraries
library(RMariaDB)
library(DBI)
library(ggplot2)
library(scales)
```


```{r}
#Define our variables. 
#Visit MySQL Workbench for the localport number, host and user.
localuserpassword <- "******" 
localport <- 3306 
db_name <- "salaryweb_db" 
```


```{r}
#Connect to the server using MariaDB()
con <- dbConnect(RMariaDB::MariaDB(), 
                 host = 'localhost',
                 user = 'root',
                 password = localuserpassword,
                 port = localport)
```


```{r}
#Create your first database integrated with MySQL Workbench. Use:
dbExecute(con, paste("CREATE DATABASE IF NOT EXISTS ", db_name))
#This code will create the database if it does not already exist with the db_name you defined above.

#If you have multiple databases, it is important to specify what database you are using.
#This especially applies if you have reused code to create multiple databases
dbExecute(con, paste("USE", db_name))

```

```{r}
#Read in the CLEAN .csv file we will use to populate our database. 
salaryweb_csv <- read.csv("cleaned_salaries.csv")
```

```{r}
#Rename the first column to employee_id
colnames(salaryweb_csv)[1] <- "employee_id"
```

```{r}
#Show rows
head(salaryweb_csv)
```

```{r}
#Create Employee table
first_table_query <- "CREATE TABLE employee ( 
                    employee_id INT AUTO_INCREMENT PRIMARY KEY,
                    job_title TEXT,
                    experience_level VARCHAR(50),
                    employment_type TEXT,
                    work_models TEXT,
                    work_year VARCHAR(10)
                                              );"
#Execute the query:
dbExecute(con, first_table_query)
```

```{r}
#Table name created
table_name <- "employee"

#Write a query that will show the column names from the table we created
query <- paste("SHOW COLUMNS FROM", table_name)

#Get the query and retrieve the column/field names from the database(con)
db_columns <- dbGetQuery(con, query)$Field

#Define the common columns between the CSV data (Column names) and the database (Table fields)
common_columns <- intersect(colnames(salaryweb_csv), db_columns)

```

```{r}
#Create a subset of the original .csv data with only the specified column names.
employee_subset <- salaryweb_csv[, common_columns]
```

```{r}
#Write data frame to database table
dbWriteTable(con, "employee", employee_subset, append = TRUE, row.names = FALSE)
```


```{r}
#Create Salaries table
second_table_query <- "CREATE TABLE salaries ( 
                    salary_id INT AUTO_INCREMENT PRIMARY KEY,
                    employee_id INT,
                    salary INT, 
                    salary_currency TEXT,
                    salary_in_usd INT,
                    FOREIGN KEY (employee_id) REFERENCES employee(employee_id)
                                              );"

dbExecute(con, second_table_query)
```

```{r}
#There are multiple ways to populate the fields of the table. 
#Another option is to add a subset of the data into data table, and then populate the database table.

#This is our table name we created
table_name <- "salaries"

#Write a query that will show the column names from the table we created
query <- paste("SHOW COLUMNS FROM", table_name)

#Get the query and retrieve the column/field names from the database(con)
db_columns <- dbGetQuery(con, query)$Field

#Define the common columns between the CSV data (Column names) and the database (Table fields)
common_columns <- intersect(colnames(salaryweb_csv), db_columns)

```


```{r}
#Create a subset of the original .csv data turtles with only the specified column names.
salaries_subset <- salaryweb_csv[, common_columns]
```

```{r}
#Write data frame to database table
dbWriteTable(con, "salaries", salaries_subset, append = TRUE, row.names = FALSE)
```


```{r}
#Create location table
third_table_query <- "CREATE TABLE location ( 
                    location_id INT AUTO_INCREMENT PRIMARY KEY,
                    employee_id INT,
                    employee_residence TEXT,
                    company_location TEXT,
                    company_size TEXT,
                    FOREIGN KEY (employee_id) REFERENCES employee(employee_id)
                                              );"

dbExecute(con, third_table_query)
```


```{r}
#Test query
#What are the top 10 unique employee residences with the highest number of employees?
query <- "SELECT employee_residence, COUNT(*) AS num_employees 
          FROM location 
          GROUP BY employee_residence 
          ORDER BY num_employees DESC 
          LIMIT 10"
result <- dbGetQuery(con, query)
print(result)
```

```{r}
#There are multiple ways to populate the fields of the table. 
#Another option is to add a subset of the data into data table, and then populate the database table.

#This is our table name we created
table_name <- "location"

#Write a query that will show the column names from the table we created
query <- paste("SHOW COLUMNS FROM", table_name)

#Get the query and retrieve the column/field names from the database(con)
db_columns <- dbGetQuery(con, query)$Field

#Define the common columns between the CSV data (Column names) and the database (Table fields)
common_columns <- intersect(colnames(salaryweb_csv), db_columns)
```

```{r}
#Create a subset of the original .csv data turtles with only the specified column names.
location_subset <- salaryweb_csv[, common_columns]
```

```{r}
#Write data frame to database table
dbWriteTable(con, "location", location_subset, append = TRUE, row.names = FALSE)
```


```{r}
#Question: What are the job positions with the highest average salaries?
top_sal <- "SELECT e.job_title, AVG(s.salary_in_usd) AS average_salary
          FROM employee e
          JOIN salaries s ON e.employee_id = s.employee_id
          GROUP BY e.job_title
          ORDER BY average_salary DESC
          LIMIT 10;"

#Execute the query
top_sal_result <- dbGetQuery(con, top_sal)

#Print results
print(top_sal_result)
```

```{r}
#Question: How do salaries differ based on experience level?
exp_level <- "SELECT e.experience_level, AVG(s.salary_in_usd) AS average_salary
          FROM employee e
          JOIN salaries s ON e.employee_id = s.employee_id
          GROUP BY e.experience_level
          ORDER BY average_salary DESC
          LIMIT 20;"

#Execute the query 
exp_result <- dbGetQuery(con, exp_level)

#Print results
print(exp_result)
```


```{r}
#Question:How does location affect salaries and what are some of the best locations for highest salaries?

loc_sal <- "SELECT l.employee_residence, AVG(s.salary_in_usd) AS average_salary
          FROM salaries s
          JOIN location l ON s.employee_id = l.employee_id
          GROUP BY l.employee_residence
          ORDER BY average_salary DESC
          LIMIT 20;"

#Execute the query and retrieve the results
loc_result <- dbGetQuery(con, loc_sal)

#Print the results
print(loc_result)

```

```{r}
salaries_data <- dbGetQuery(con, "SELECT salary FROM salaries")

#Create histogram to show distribution of salaries
ggplot(salaries_data, aes(x = salary)) +
  geom_histogram(binwidth = 500000, fill = "lightsalmon1", alpha = 0.7) +
  labs(
    title = "Distribution of Salaries",
    x = "Salary",
    y = "Frequency"
  ) +
  theme_minimal() +
  theme(
    plot.title = element_text(size = 17, hjust = 0.5),
    axis.text = element_text(size = 14),
    axis.title = element_text(size = 16)
  ) +
  scale_x_continuous(labels = comma_format(), limits = c(0, 8100000)) +  #Add x-axis labels with commas and set limits
  coord_cartesian(ylim = c(0, 20)) +  #Set the y-axis limits
  expand_limits(x = 0)  #Make sure x-axis starts from 0
```


```{r}
#Query to get average salaries by experience level
query_experience <- "SELECT experience_level, AVG(salary_in_usd) as avg_salary 
                     FROM employee 
                     JOIN salaries ON employee.employee_id = salaries.employee_id 
                     GROUP BY experience_level"

#Execute query and fetch data
data_experience <- dbGetQuery(con, query_experience)

#Bar chart for average salaries by experience level
ggplot(data_experience, aes(x = experience_level, y = avg_salary, fill = experience_level)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::dollar) +
  labs(title = "Average Salaries by Experience Level", y = "Average Salary", x = "Experience Level") +
  theme_minimal()
```


```{r}
#Query to get average salaries by employment type
query_employment <- "SELECT employment_type, AVG(salary_in_usd) as avg_salary 
                     FROM employee 
                     JOIN salaries ON employee.employee_id = salaries.employee_id 
                     GROUP BY employment_type"

#Execute query
data_employment <- dbGetQuery(con, query_employment)

#Bar chart for average salaries by employment type
ggplot(data_employment, aes(x = employment_type, y = avg_salary, fill = employment_type)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::dollar) +
  labs(title = "Average Salaries by Employment Type", y = "Average Salary", x = "Employment Type") +
  theme_minimal()
```
```{r}
#Query to get average salaries by work models
query_models <- "SELECT work_models, AVG(salary_in_usd) as avg_salary 
                      FROM employee 
                      JOIN salaries ON employee.employee_id = salaries.employee_id 
                      GROUP BY work_models"

# Execute query and fetch data
data_models <- dbGetQuery(con, query_models)

# Bar chart for average salaries by work models
ggplot(data_models, aes(x = work_models, y = avg_salary, fill = work_models)) +
  geom_bar(stat = "identity") +
  scale_y_continuous(labels = scales::dollar) +
  labs(title = "Average Salaries by Work Models", y = "Average Salary", x = "Work Models") +
  theme_minimal()
```

```{r}
#Close the database connection 
dbDisconnect(con)
```

